language: node_js
node_js:
  - node
  - 7
  - 6

env:
  - NODE_ENV=travis

before_install:
  - npm install portfinder coveralls codacy-coverage @angular/cli -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage

notifications:
   email:
     - flaesch.arnaud@esgi.fr
